apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c30djv9do-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c30djv9do-python 
  name: c30djv9do-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c30djv9do-python 
